/* Generated by itemis CREATE code generator. */

#ifndef HELLOSC_H_
#define HELLOSC_H_

/*!
Forward declaration for the HelloSC state machine.
*/
class HelloSC;


#include "sc_types.h"
#include "sc_statemachine.h"
#include "sc_cyclebased.h"
#include "sc_timer.h"
#include <string.h>

/*! \file
Header of the state machine 'HelloSC'.
*/


class HelloSC : public sc::timer::TimedInterface, public sc::CycleBasedInterface
{
	public:
		HelloSC() noexcept;
		
		virtual ~HelloSC();
		
		
		
		/*! Enumeration of all states. */
		enum class State
		{
			NO_STATE,
			main_region_On,
			main_region_Off,
			timer_sc_Timer_Off,
			timer_sc_Timer_On,
			ui_sc_NO_OP,
			ui_sc_SET_PERIOD,
			ui_sc_RESET,
			ui_sc_CHANGE_PERIOD
		};
		
		/*! The number of states. */
		static constexpr const sc::integer numStates {8};
		static constexpr const sc::integer scvi_main_region_On {0};
		static constexpr const sc::integer scvi_main_region_Off {0};
		static constexpr const sc::integer scvi_timer_sc_Timer_Off {1};
		static constexpr const sc::integer scvi_timer_sc_Timer_On {1};
		static constexpr const sc::integer scvi_ui_sc_NO_OP {2};
		static constexpr const sc::integer scvi_ui_sc_SET_PERIOD {2};
		static constexpr const sc::integer scvi_ui_sc_RESET {2};
		static constexpr const sc::integer scvi_ui_sc_CHANGE_PERIOD {2};
		
		
		/*! Gets the value of the variable 'led' that is defined in the default interface scope. */
		bool getLed() const noexcept;
		/*! Sets the value of the variable 'led' that is defined in the default interface scope. */
		void setLed(bool led) noexcept;
		//! Inner class for default interface scope operation callbacks.
		class OperationCallback
		{
			public:
				virtual ~OperationCallback() = 0;
				
				virtual void synchronize() = 0;
				
				virtual void setPeriod() = 0;
				
				virtual void reset() = 0;
				
				virtual void noOP() = 0;
				
				virtual void inc() = 0;
				
				virtual void dec() = 0;
				
				
		};
		
		/*! Set the working instance of the operation callback interface 'OperationCallback'. */
		void setOperationCallback(OperationCallback* operationCallback) noexcept;
		//! Inner class for Timer interface scope.
		class Timer
		{
			public:
				explicit Timer(HelloSC* parent) noexcept;
				
				
				
				
				/*! Gets the value of the variable 'period' that is defined in the interface scope 'Timer'. */
				sc::integer getPeriod() const noexcept;
				
				/*! Sets the value of the variable 'period' that is defined in the interface scope 'Timer'. */
				void setPeriod(sc::integer period) noexcept;
				
				/*! Raises the in event 'timeout' of interface scope 'Timer'. */
				void raiseTimeout() noexcept;
				/*! Raises the in event 'toggle' of interface scope 'Timer'. */
				void raiseToggle() noexcept;
				
				
				
			private:
				friend class HelloSC;
				
				sc::integer period {500};
				
				/*! Indicates event 'timeout' of interface scope 'Timer' is active. */
				bool timeout_raised {false};
				/*! Indicates event 'toggle' of interface scope 'Timer' is active. */
				bool toggle_raised {false};
				
				HelloSC* parent;
				
				
				
				
				
		};
		
		/*! Returns an instance of the interface class 'Timer'. */
		Timer& timer() noexcept;
		
		//! Inner class for UI interface scope.
		class UI
		{
			public:
				explicit UI(HelloSC* parent) noexcept;
				
				
				
				
				
				
				/*! Gets the value of the variable 'STEP' that is defined in the interface scope 'UI'. */
				static sc::integer getSTEP()  noexcept;
				
				/*! Gets the value of the variable 'RESET' that is defined in the interface scope 'UI'. */
				static sc::integer getRESET()  noexcept;
				
				/*! Gets the value of the variable 'TOUT' that is defined in the interface scope 'UI'. */
				static sc::integer getTOUT()  noexcept;
				
				/*! Raises the in event 'btn1' of interface scope 'UI'. */
				void raiseBtn1() noexcept;
				/*! Raises the in event 'btn2' of interface scope 'UI'. */
				void raiseBtn2() noexcept;
				
				
				
			private:
				friend class HelloSC;
				
				static constexpr const sc::integer STEP {100};
				static constexpr const sc::integer RESET {500};
				static constexpr const sc::integer TOUT {5};
				
				/*! Indicates event 'btn1' of interface scope 'UI' is active. */
				bool btn1_raised {false};
				/*! Indicates event 'btn2' of interface scope 'UI' is active. */
				bool btn2_raised {false};
				
				HelloSC* parent;
				
				
				
				
				
		};
		
		/*! Returns an instance of the interface class 'UI'. */
		UI& uI() noexcept;
		
		
		
		/*
		 * Functions inherited from StatemachineInterface
		 */
		 void enter() override;
		
		 void exit() override;
		
		void runCycle() override;
		
		/*!
		 * Checks if the state machine is active (until 2.4.1 this method was used for states).
		 * A state machine is active if it has been entered. It is inactive if it has not been entered at all or if it has been exited.
		 */
		 bool isActive() const noexcept override;
		
		
		/*!
		* Checks if all active states are final. 
		* If there are no active states then the state machine is considered being inactive. In this case this method returns false.
		*/
		 bool isFinal() const noexcept override;
		
		/*! 
		 * Checks if member of the state machine must be set. For example an operation callback.
		 */
		bool check() const noexcept;
		
		/*
		 * Functions inherited from TimedStatemachineInterface
		 */
		void setTimerService(sc::timer::TimerServiceInterface* timerService_) noexcept override;
		
		sc::timer::TimerServiceInterface* getTimerService() noexcept override;
		
		void raiseTimeEvent(sc::eventid event) noexcept override;
		
		sc::integer getNumberOfParallelTimeEvents() noexcept override;
		
		
		
		/*! Checks if the specified state is active (until 2.4.1 the used method for states was calles isActive()). */
		bool isStateActive(State state) const noexcept;
		
		//! number of time events used by the state machine.
		static const sc::integer timeEventsCount {5};
		
		//! number of time events that can be active at once.
		static const sc::integer parallelTimeEventsCount {3};
		
		
	protected:
		
		
		
		
	private:
		HelloSC(const HelloSC &rhs);
		HelloSC& operator=(const HelloSC&);
		
		bool led {false};
		
		
		
		
		
		//! the maximum number of orthogonal states defines the dimension of the state configuration vector.
		static const sc::ushort maxOrthogonalStates {3};
		
		sc::timer::TimerServiceInterface* timerService;
		bool timeEvents[timeEventsCount];
		
		
		State stateConfVector[maxOrthogonalStates];
		
		
		Timer ifaceTimer {Timer{nullptr}};
		UI ifaceUI {UI{nullptr}};
		
		OperationCallback* ifaceOperationCallback;
		
		typedef struct {
			bool timeout_raised;
			bool toggle_raised;
		}HelloSCIfaceTimerEvBuf;
		typedef struct {
			bool btn1_raised;
			bool btn2_raised;
		}HelloSCIfaceUIEvBuf;
		typedef struct {
			bool HelloSC_timer_sc_Timer_On_time_event_0_raised;
			bool HelloSC_ui_sc_SET_PERIOD_time_event_0_raised;
			bool HelloSC_ui_sc_RESET_time_event_0_raised;
			bool HelloSC_ui_sc_CHANGE_PERIOD_time_event_0_raised;
			bool HelloSC_time_event_0_raised;
		}HelloSCTimeEventsEvBuf;
		typedef struct {
			HelloSCIfaceTimerEvBuf ifaceTimer;
			HelloSCIfaceUIEvBuf ifaceUI;
			HelloSCTimeEventsEvBuf timeEvents;
		}HelloSCEvBuf;
		HelloSCEvBuf current {};
		bool isExecuting {false};
		sc::integer stateConfVectorPosition {0};
		
		
		
		// prototypes of all internal functions
		
		void enact_main_region_On();
		void enact_main_region_Off();
		void enact_timer_sc_Timer_On();
		void enact_ui_sc_NO_OP();
		void enact_ui_sc_SET_PERIOD();
		void enact_ui_sc_RESET();
		void enact_ui_sc_CHANGE_PERIOD();
		void exact_timer_sc_Timer_On();
		void exact_ui_sc_SET_PERIOD();
		void exact_ui_sc_RESET();
		void exact_ui_sc_CHANGE_PERIOD();
		void enseq_main_region_On_default();
		void enseq_main_region_Off_default();
		void enseq_timer_sc_Timer_Off_default();
		void enseq_timer_sc_Timer_On_default();
		void enseq_ui_sc_NO_OP_default();
		void enseq_ui_sc_SET_PERIOD_default();
		void enseq_ui_sc_RESET_default();
		void enseq_ui_sc_CHANGE_PERIOD_default();
		void enseq_main_region_default();
		void enseq_timer_sc_default();
		void enseq_ui_sc_default();
		void exseq_main_region_On();
		void exseq_main_region_Off();
		void exseq_timer_sc_Timer_Off();
		void exseq_timer_sc_Timer_On();
		void exseq_ui_sc_NO_OP();
		void exseq_ui_sc_SET_PERIOD();
		void exseq_ui_sc_RESET();
		void exseq_ui_sc_CHANGE_PERIOD();
		void exseq_main_region();
		void exseq_timer_sc();
		void exseq_ui_sc();
		void react_main_region__entry_Default();
		void react_timer_sc__entry_Default();
		void react_ui_sc__entry_Default();
		sc::integer react(const sc::integer transitioned_before);
		sc::integer main_region_On_react(const sc::integer transitioned_before);
		sc::integer main_region_Off_react(const sc::integer transitioned_before);
		sc::integer timer_sc_Timer_Off_react(const sc::integer transitioned_before);
		sc::integer timer_sc_Timer_On_react(const sc::integer transitioned_before);
		sc::integer ui_sc_NO_OP_react(const sc::integer transitioned_before);
		sc::integer ui_sc_SET_PERIOD_react(const sc::integer transitioned_before);
		sc::integer ui_sc_RESET_react(const sc::integer transitioned_before);
		sc::integer ui_sc_CHANGE_PERIOD_react(const sc::integer transitioned_before);
		void swapInEvents() noexcept;
		void clearInEvents() noexcept;
		void microStep();
		
		
		
		
		
};


inline HelloSC::OperationCallback::~OperationCallback() {}


#endif /* HELLOSC_H_ */
