/* Generated by itemis CREATE code generator. */

#include "HelloSC.h"

/*! \file
Implementation of the state machine 'HelloSC'
*/




HelloSC::HelloSC() noexcept
{
	this->ifaceTimer.parent = this;
	this->ifaceUI.parent = this;
	for (sc::ushort state_vec_pos = 0; state_vec_pos < maxOrthogonalStates; ++state_vec_pos)
		stateConfVector[state_vec_pos] = HelloSC::State::NO_STATE;
	
	clearInEvents();
	swapInEvents();
}

HelloSC::~HelloSC()
{
}

HelloSC::Timer::Timer(HelloSC* parent_) noexcept :
	parent(parent_)
{
}

HelloSC::UI::UI(HelloSC* parent_) noexcept :
	parent(parent_)
{
}




bool HelloSC::isActive() const noexcept
{
	return stateConfVector[0] != HelloSC::State::NO_STATE||stateConfVector[1] != HelloSC::State::NO_STATE||stateConfVector[2] != HelloSC::State::NO_STATE;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
bool HelloSC::isFinal() const noexcept
{
	return false;
}

bool HelloSC::check() const noexcept
{
	if(timerService == nullptr) {
		return false;
	}
	if (this->ifaceOperationCallback == nullptr) {
		return false;
	}
	return true;
}


void HelloSC::setTimerService(sc::timer::TimerServiceInterface* timerService_) noexcept
{
	this->timerService = timerService_;
}

sc::timer::TimerServiceInterface* HelloSC::getTimerService() noexcept
{
	return timerService;
}

sc::integer HelloSC::getNumberOfParallelTimeEvents() noexcept {
	return parallelTimeEventsCount;
}

void HelloSC::raiseTimeEvent(sc::eventid evid) noexcept
{
	if (evid < timeEventsCount)
	{
		timeEvents[evid] = true;
	}
}


bool HelloSC::isStateActive(State state) const noexcept
{
	switch (state)
	{
		case HelloSC::State::main_region_On :
		{
			return  (stateConfVector[scvi_main_region_On] == HelloSC::State::main_region_On);
			break;
		}
		case HelloSC::State::main_region_Off :
		{
			return  (stateConfVector[scvi_main_region_Off] == HelloSC::State::main_region_Off);
			break;
		}
		case HelloSC::State::timer_sc_Timer_Off :
		{
			return  (stateConfVector[scvi_timer_sc_Timer_Off] == HelloSC::State::timer_sc_Timer_Off);
			break;
		}
		case HelloSC::State::timer_sc_Timer_On :
		{
			return  (stateConfVector[scvi_timer_sc_Timer_On] == HelloSC::State::timer_sc_Timer_On);
			break;
		}
		case HelloSC::State::ui_sc_NO_OP :
		{
			return  (stateConfVector[scvi_ui_sc_NO_OP] == HelloSC::State::ui_sc_NO_OP);
			break;
		}
		case HelloSC::State::ui_sc_SET_PERIOD :
		{
			return  (stateConfVector[scvi_ui_sc_SET_PERIOD] == HelloSC::State::ui_sc_SET_PERIOD);
			break;
		}
		case HelloSC::State::ui_sc_RESET :
		{
			return  (stateConfVector[scvi_ui_sc_RESET] == HelloSC::State::ui_sc_RESET);
			break;
		}
		case HelloSC::State::ui_sc_CHANGE_PERIOD :
		{
			return  (stateConfVector[scvi_ui_sc_CHANGE_PERIOD] == HelloSC::State::ui_sc_CHANGE_PERIOD);
			break;
		}
		default:
		{
			/* State is not active*/
			return false;
			break;
		}
	}
}

bool HelloSC::getLed() const noexcept
{
	return led
	;
}

void HelloSC::setLed(bool led_) noexcept
{
	this->led = led_;
}
void HelloSC::setOperationCallback(OperationCallback* operationCallback) noexcept
{
	ifaceOperationCallback = operationCallback;
}
HelloSC::Timer& HelloSC::timer() noexcept
{
	return ifaceTimer;
}
sc::integer HelloSC::Timer::getPeriod() const noexcept
{
	return period
	;
}

void HelloSC::Timer::setPeriod(sc::integer period_) noexcept
{
	this->period = period_;
}

/*! Raises the in event 'timeout' of interface scope 'Timer'. */
void HelloSC::Timer::raiseTimeout() noexcept {
	timeout_raised = true;
}


/*! Raises the in event 'toggle' of interface scope 'Timer'. */
void HelloSC::Timer::raiseToggle() noexcept {
	toggle_raised = true;
}

HelloSC::UI& HelloSC::uI() noexcept
{
	return ifaceUI;
}
sc::integer HelloSC::UI::getSTEP() noexcept
{
	return STEP
	;
}

sc::integer HelloSC::UI::getRESET() noexcept
{
	return RESET
	;
}

sc::integer HelloSC::UI::getTOUT() noexcept
{
	return TOUT
	;
}


/*! Raises the in event 'btn1' of interface scope 'UI'. */
void HelloSC::UI::raiseBtn1() noexcept {
	btn1_raised = true;
}


/*! Raises the in event 'btn2' of interface scope 'UI'. */
void HelloSC::UI::raiseBtn2() noexcept {
	btn2_raised = true;
}


// implementations of all internal functions
/* Entry action for state 'On'. */
void HelloSC::enact_main_region_On()
{
	/* Entry action for state 'On'. */
	setLed(true);
}

/* Entry action for state 'Off'. */
void HelloSC::enact_main_region_Off()
{
	/* Entry action for state 'Off'. */
	setLed(false);
}

/* Entry action for state 'Timer_On'. */
void HelloSC::enact_timer_sc_Timer_On()
{
	/* Entry action for state 'Timer_On'. */
	timerService->setTimer(this, 0, ((static_cast<sc::time> (ifaceTimer.period)) * 1), false);
	ifaceTimer.timeout_raised = true;
}

/* Entry action for state 'NO_OP'. */
void HelloSC::enact_ui_sc_NO_OP()
{
	/* Entry action for state 'NO_OP'. */
	ifaceOperationCallback->noOP();
}

/* Entry action for state 'SET_PERIOD'. */
void HelloSC::enact_ui_sc_SET_PERIOD()
{
	/* Entry action for state 'SET_PERIOD'. */
	timerService->setTimer(this, 1, (((static_cast<sc::time> (HelloSC::UI::TOUT)) * 1) * 1000), false);
	ifaceOperationCallback->setPeriod();
}

/* Entry action for state 'RESET'. */
void HelloSC::enact_ui_sc_RESET()
{
	/* Entry action for state 'RESET'. */
	timerService->setTimer(this, 2, (((static_cast<sc::time> (HelloSC::UI::TOUT)) * 1) * 1000), false);
	ifaceOperationCallback->reset();
}

/* Entry action for state 'CHANGE_PERIOD'. */
void HelloSC::enact_ui_sc_CHANGE_PERIOD()
{
	/* Entry action for state 'CHANGE_PERIOD'. */
	timerService->setTimer(this, 3, (((static_cast<sc::time> (HelloSC::UI::TOUT)) * 1) * 1000), false);
}

/* Exit action for state 'Timer_On'. */
void HelloSC::exact_timer_sc_Timer_On()
{
	/* Exit action for state 'Timer_On'. */
	timerService->unsetTimer(this, 0);
}

/* Exit action for state 'SET_PERIOD'. */
void HelloSC::exact_ui_sc_SET_PERIOD()
{
	/* Exit action for state 'SET_PERIOD'. */
	timerService->unsetTimer(this, 1);
}

/* Exit action for state 'RESET'. */
void HelloSC::exact_ui_sc_RESET()
{
	/* Exit action for state 'RESET'. */
	timerService->unsetTimer(this, 2);
}

/* Exit action for state 'CHANGE_PERIOD'. */
void HelloSC::exact_ui_sc_CHANGE_PERIOD()
{
	/* Exit action for state 'CHANGE_PERIOD'. */
	timerService->unsetTimer(this, 3);
}

/* 'default' enter sequence for state On */
void HelloSC::enseq_main_region_On_default()
{
	/* 'default' enter sequence for state On */
	enact_main_region_On();
	stateConfVector[0] = HelloSC::State::main_region_On;
	stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state Off */
void HelloSC::enseq_main_region_Off_default()
{
	/* 'default' enter sequence for state Off */
	enact_main_region_Off();
	stateConfVector[0] = HelloSC::State::main_region_Off;
	stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state Timer_Off */
void HelloSC::enseq_timer_sc_Timer_Off_default()
{
	/* 'default' enter sequence for state Timer_Off */
	stateConfVector[1] = HelloSC::State::timer_sc_Timer_Off;
	stateConfVectorPosition = 1;
}

/* 'default' enter sequence for state Timer_On */
void HelloSC::enseq_timer_sc_Timer_On_default()
{
	/* 'default' enter sequence for state Timer_On */
	enact_timer_sc_Timer_On();
	stateConfVector[1] = HelloSC::State::timer_sc_Timer_On;
	stateConfVectorPosition = 1;
}

/* 'default' enter sequence for state NO_OP */
void HelloSC::enseq_ui_sc_NO_OP_default()
{
	/* 'default' enter sequence for state NO_OP */
	enact_ui_sc_NO_OP();
	stateConfVector[2] = HelloSC::State::ui_sc_NO_OP;
	stateConfVectorPosition = 2;
}

/* 'default' enter sequence for state SET_PERIOD */
void HelloSC::enseq_ui_sc_SET_PERIOD_default()
{
	/* 'default' enter sequence for state SET_PERIOD */
	enact_ui_sc_SET_PERIOD();
	stateConfVector[2] = HelloSC::State::ui_sc_SET_PERIOD;
	stateConfVectorPosition = 2;
}

/* 'default' enter sequence for state RESET */
void HelloSC::enseq_ui_sc_RESET_default()
{
	/* 'default' enter sequence for state RESET */
	enact_ui_sc_RESET();
	stateConfVector[2] = HelloSC::State::ui_sc_RESET;
	stateConfVectorPosition = 2;
}

/* 'default' enter sequence for state CHANGE_PERIOD */
void HelloSC::enseq_ui_sc_CHANGE_PERIOD_default()
{
	/* 'default' enter sequence for state CHANGE_PERIOD */
	enact_ui_sc_CHANGE_PERIOD();
	stateConfVector[2] = HelloSC::State::ui_sc_CHANGE_PERIOD;
	stateConfVectorPosition = 2;
}

/* 'default' enter sequence for region main region */
void HelloSC::enseq_main_region_default()
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default();
}

/* 'default' enter sequence for region timer_sc */
void HelloSC::enseq_timer_sc_default()
{
	/* 'default' enter sequence for region timer_sc */
	react_timer_sc__entry_Default();
}

/* 'default' enter sequence for region ui_sc */
void HelloSC::enseq_ui_sc_default()
{
	/* 'default' enter sequence for region ui_sc */
	react_ui_sc__entry_Default();
}

/* Default exit sequence for state On */
void HelloSC::exseq_main_region_On()
{
	/* Default exit sequence for state On */
	stateConfVector[0] = HelloSC::State::NO_STATE;
	stateConfVectorPosition = 0;
}

/* Default exit sequence for state Off */
void HelloSC::exseq_main_region_Off()
{
	/* Default exit sequence for state Off */
	stateConfVector[0] = HelloSC::State::NO_STATE;
	stateConfVectorPosition = 0;
}

/* Default exit sequence for state Timer_Off */
void HelloSC::exseq_timer_sc_Timer_Off()
{
	/* Default exit sequence for state Timer_Off */
	stateConfVector[1] = HelloSC::State::NO_STATE;
	stateConfVectorPosition = 1;
}

/* Default exit sequence for state Timer_On */
void HelloSC::exseq_timer_sc_Timer_On()
{
	/* Default exit sequence for state Timer_On */
	stateConfVector[1] = HelloSC::State::NO_STATE;
	stateConfVectorPosition = 1;
	exact_timer_sc_Timer_On();
}

/* Default exit sequence for state NO_OP */
void HelloSC::exseq_ui_sc_NO_OP()
{
	/* Default exit sequence for state NO_OP */
	stateConfVector[2] = HelloSC::State::NO_STATE;
	stateConfVectorPosition = 2;
}

/* Default exit sequence for state SET_PERIOD */
void HelloSC::exseq_ui_sc_SET_PERIOD()
{
	/* Default exit sequence for state SET_PERIOD */
	stateConfVector[2] = HelloSC::State::NO_STATE;
	stateConfVectorPosition = 2;
	exact_ui_sc_SET_PERIOD();
}

/* Default exit sequence for state RESET */
void HelloSC::exseq_ui_sc_RESET()
{
	/* Default exit sequence for state RESET */
	stateConfVector[2] = HelloSC::State::NO_STATE;
	stateConfVectorPosition = 2;
	exact_ui_sc_RESET();
}

/* Default exit sequence for state CHANGE_PERIOD */
void HelloSC::exseq_ui_sc_CHANGE_PERIOD()
{
	/* Default exit sequence for state CHANGE_PERIOD */
	stateConfVector[2] = HelloSC::State::NO_STATE;
	stateConfVectorPosition = 2;
	exact_ui_sc_CHANGE_PERIOD();
}

/* Default exit sequence for region main region */
void HelloSC::exseq_main_region()
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of HelloSC.main_region) at position 0... */
	switch(stateConfVector[ 0 ])
	{
		case HelloSC::State::main_region_On :
		{
			exseq_main_region_On();
			break;
		}
		case HelloSC::State::main_region_Off :
		{
			exseq_main_region_Off();
			break;
		}
		default:
			/* do nothing */
			break;
	}
}

/* Default exit sequence for region timer_sc */
void HelloSC::exseq_timer_sc()
{
	/* Default exit sequence for region timer_sc */
	/* Handle exit of all possible states (of HelloSC.timer_sc) at position 1... */
	switch(stateConfVector[ 1 ])
	{
		case HelloSC::State::timer_sc_Timer_Off :
		{
			exseq_timer_sc_Timer_Off();
			break;
		}
		case HelloSC::State::timer_sc_Timer_On :
		{
			exseq_timer_sc_Timer_On();
			break;
		}
		default:
			/* do nothing */
			break;
	}
}

/* Default exit sequence for region ui_sc */
void HelloSC::exseq_ui_sc()
{
	/* Default exit sequence for region ui_sc */
	/* Handle exit of all possible states (of HelloSC.ui_sc) at position 2... */
	switch(stateConfVector[ 2 ])
	{
		case HelloSC::State::ui_sc_NO_OP :
		{
			exseq_ui_sc_NO_OP();
			break;
		}
		case HelloSC::State::ui_sc_SET_PERIOD :
		{
			exseq_ui_sc_SET_PERIOD();
			break;
		}
		case HelloSC::State::ui_sc_RESET :
		{
			exseq_ui_sc_RESET();
			break;
		}
		case HelloSC::State::ui_sc_CHANGE_PERIOD :
		{
			exseq_ui_sc_CHANGE_PERIOD();
			break;
		}
		default:
			/* do nothing */
			break;
	}
}

/* Default react sequence for initial entry  */
void HelloSC::react_main_region__entry_Default()
{
	/* Default react sequence for initial entry  */
	enseq_main_region_On_default();
}

/* Default react sequence for initial entry  */
void HelloSC::react_timer_sc__entry_Default()
{
	/* Default react sequence for initial entry  */
	enseq_timer_sc_Timer_Off_default();
}

/* Default react sequence for initial entry  */
void HelloSC::react_ui_sc__entry_Default()
{
	/* Default react sequence for initial entry  */
	enseq_ui_sc_NO_OP_default();
}

sc::integer HelloSC::react(const sc::integer transitioned_before) {
	/* State machine reactions. */
	if (current.timeEvents.HelloSC_time_event_0_raised)
	{ 
		ifaceOperationCallback->synchronize();
	} 
	return transitioned_before;
}

sc::integer HelloSC::main_region_On_react(const sc::integer transitioned_before) {
	/* The reactions of state On. */
	sc::integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (current.ifaceTimer.timeout_raised)
		{ 
			exseq_main_region_On();
			enseq_main_region_Off_default();
			transitioned_after = 0;
		} 
	} 
	return transitioned_after;
}

sc::integer HelloSC::main_region_Off_react(const sc::integer transitioned_before) {
	/* The reactions of state Off. */
	sc::integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (current.ifaceTimer.timeout_raised)
		{ 
			exseq_main_region_Off();
			enseq_main_region_On_default();
			transitioned_after = 0;
		} 
	} 
	return transitioned_after;
}

sc::integer HelloSC::timer_sc_Timer_Off_react(const sc::integer transitioned_before) {
	/* The reactions of state Timer_Off. */
	sc::integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (1))
	{ 
		if (current.ifaceTimer.toggle_raised)
		{ 
			exseq_timer_sc_Timer_Off();
			enseq_timer_sc_Timer_On_default();
			transitioned_after = 1;
		} 
	} 
	return transitioned_after;
}

sc::integer HelloSC::timer_sc_Timer_On_react(const sc::integer transitioned_before) {
	/* The reactions of state Timer_On. */
	sc::integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (1))
	{ 
		if (current.ifaceTimer.toggle_raised)
		{ 
			exseq_timer_sc_Timer_On();
			enseq_timer_sc_Timer_Off_default();
			transitioned_after = 1;
		}  else
		{
			if (current.timeEvents.HelloSC_timer_sc_Timer_On_time_event_0_raised)
			{ 
				exseq_timer_sc_Timer_On();
				current.timeEvents.HelloSC_timer_sc_Timer_On_time_event_0_raised = false;
				enseq_timer_sc_Timer_On_default();
				transitioned_after = 1;
			} 
		}
	} 
	return transitioned_after;
}

sc::integer HelloSC::ui_sc_NO_OP_react(const sc::integer transitioned_before) {
	/* The reactions of state NO_OP. */
	sc::integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (2))
	{ 
		if (current.ifaceUI.btn1_raised)
		{ 
			exseq_ui_sc_NO_OP();
			enseq_ui_sc_SET_PERIOD_default();
			react(0);
			transitioned_after = 2;
		} 
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = react(transitioned_before);
	} 
	return transitioned_after;
}

sc::integer HelloSC::ui_sc_SET_PERIOD_react(const sc::integer transitioned_before) {
	/* The reactions of state SET_PERIOD. */
	sc::integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (2))
	{ 
		if (current.ifaceUI.btn1_raised)
		{ 
			exseq_ui_sc_SET_PERIOD();
			enseq_ui_sc_RESET_default();
			react(0);
			transitioned_after = 2;
		}  else
		{
			if (current.ifaceUI.btn2_raised)
			{ 
				exseq_ui_sc_SET_PERIOD();
				enseq_ui_sc_CHANGE_PERIOD_default();
				react(0);
				transitioned_after = 2;
			}  else
			{
				if (current.timeEvents.HelloSC_ui_sc_SET_PERIOD_time_event_0_raised)
				{ 
					exseq_ui_sc_SET_PERIOD();
					current.timeEvents.HelloSC_ui_sc_SET_PERIOD_time_event_0_raised = false;
					enseq_ui_sc_NO_OP_default();
					react(0);
					transitioned_after = 2;
				} 
			}
		}
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = react(transitioned_before);
	} 
	return transitioned_after;
}

sc::integer HelloSC::ui_sc_RESET_react(const sc::integer transitioned_before) {
	/* The reactions of state RESET. */
	sc::integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (2))
	{ 
		if (current.ifaceUI.btn1_raised)
		{ 
			exseq_ui_sc_RESET();
			enseq_ui_sc_SET_PERIOD_default();
			react(0);
			transitioned_after = 2;
		}  else
		{
			if (current.ifaceUI.btn2_raised)
			{ 
				exseq_ui_sc_RESET();
				ifaceTimer.setPeriod(HelloSC::UI::RESET);
				enseq_ui_sc_NO_OP_default();
				react(0);
				transitioned_after = 2;
			}  else
			{
				if (current.timeEvents.HelloSC_ui_sc_RESET_time_event_0_raised)
				{ 
					exseq_ui_sc_RESET();
					current.timeEvents.HelloSC_ui_sc_RESET_time_event_0_raised = false;
					enseq_ui_sc_NO_OP_default();
					react(0);
					transitioned_after = 2;
				} 
			}
		}
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = react(transitioned_before);
	} 
	return transitioned_after;
}

sc::integer HelloSC::ui_sc_CHANGE_PERIOD_react(const sc::integer transitioned_before) {
	/* The reactions of state CHANGE_PERIOD. */
	sc::integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (2))
	{ 
		if (current.ifaceUI.btn1_raised)
		{ 
			exseq_ui_sc_CHANGE_PERIOD();
			ifaceTimer.setPeriod(ifaceTimer.period + (HelloSC::UI::STEP));
			ifaceOperationCallback->inc();
			enseq_ui_sc_CHANGE_PERIOD_default();
			react(0);
			transitioned_after = 2;
		}  else
		{
			if (current.ifaceUI.btn2_raised)
			{ 
				exseq_ui_sc_CHANGE_PERIOD();
				ifaceTimer.setPeriod(ifaceTimer.period - (HelloSC::UI::STEP));
				ifaceOperationCallback->dec();
				enseq_ui_sc_CHANGE_PERIOD_default();
				react(0);
				transitioned_after = 2;
			}  else
			{
				if (current.timeEvents.HelloSC_ui_sc_CHANGE_PERIOD_time_event_0_raised)
				{ 
					exseq_ui_sc_CHANGE_PERIOD();
					current.timeEvents.HelloSC_ui_sc_CHANGE_PERIOD_time_event_0_raised = false;
					enseq_ui_sc_SET_PERIOD_default();
					react(0);
					transitioned_after = 2;
				} 
			}
		}
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = react(transitioned_before);
	} 
	return transitioned_after;
}

void HelloSC::swapInEvents() noexcept {
	current.ifaceTimer.timeout_raised = ifaceTimer.timeout_raised;
	ifaceTimer.timeout_raised = false;
	current.ifaceTimer.toggle_raised = ifaceTimer.toggle_raised;
	ifaceTimer.toggle_raised = false;
	current.ifaceUI.btn1_raised = ifaceUI.btn1_raised;
	ifaceUI.btn1_raised = false;
	current.ifaceUI.btn2_raised = ifaceUI.btn2_raised;
	ifaceUI.btn2_raised = false;
	current.timeEvents.HelloSC_timer_sc_Timer_On_time_event_0_raised = timeEvents[0];
	timeEvents[0] = false;
	current.timeEvents.HelloSC_ui_sc_SET_PERIOD_time_event_0_raised = timeEvents[1];
	timeEvents[1] = false;
	current.timeEvents.HelloSC_ui_sc_RESET_time_event_0_raised = timeEvents[2];
	timeEvents[2] = false;
	current.timeEvents.HelloSC_ui_sc_CHANGE_PERIOD_time_event_0_raised = timeEvents[3];
	timeEvents[3] = false;
	current.timeEvents.HelloSC_time_event_0_raised = timeEvents[4];
	timeEvents[4] = false;
}

void HelloSC::clearInEvents() noexcept {
	ifaceTimer.timeout_raised = false;
	ifaceTimer.toggle_raised = false;
	ifaceUI.btn1_raised = false;
	ifaceUI.btn2_raised = false;
	timeEvents[0] = false;
	timeEvents[1] = false;
	timeEvents[2] = false;
	timeEvents[3] = false;
	timeEvents[4] = false;
}

void HelloSC::microStep() {
	sc::integer transitioned = -1;
	stateConfVectorPosition = 0;
	switch(stateConfVector[ 0 ])
	{
		case HelloSC::State::main_region_On :
		{
			transitioned = main_region_On_react(transitioned);
			break;
		}
		case HelloSC::State::main_region_Off :
		{
			transitioned = main_region_Off_react(transitioned);
			break;
		}
		default:
			/* do nothing */
			break;
	}
	if ((stateConfVectorPosition) < (1))
	{ 
		switch(stateConfVector[ 1 ])
		{
			case HelloSC::State::timer_sc_Timer_Off :
			{
				transitioned = timer_sc_Timer_Off_react(transitioned);
				break;
			}
			case HelloSC::State::timer_sc_Timer_On :
			{
				transitioned = timer_sc_Timer_On_react(transitioned);
				break;
			}
			default:
				/* do nothing */
				break;
		}
	} 
	if ((stateConfVectorPosition) < (2))
	{ 
		switch(stateConfVector[ 2 ])
		{
			case HelloSC::State::ui_sc_NO_OP :
			{
				ui_sc_NO_OP_react(transitioned);
				break;
			}
			case HelloSC::State::ui_sc_SET_PERIOD :
			{
				ui_sc_SET_PERIOD_react(transitioned);
				break;
			}
			case HelloSC::State::ui_sc_RESET :
			{
				ui_sc_RESET_react(transitioned);
				break;
			}
			case HelloSC::State::ui_sc_CHANGE_PERIOD :
			{
				ui_sc_CHANGE_PERIOD_react(transitioned);
				break;
			}
			default:
				/* do nothing */
				break;
		}
	} 
}

void HelloSC::runCycle() {
	/* Performs a 'run to completion' step. */
	if (isExecuting)
	{ 
		return;
	} 
	isExecuting = true;
	swapInEvents();
	microStep();
	isExecuting = false;
}

void HelloSC::enter() {
	/* Activates the state machine. */
	if (isExecuting)
	{ 
		return;
	} 
	isExecuting = true;
	/* Default enter sequence for statechart HelloSC */
	/* Entry action for statechart 'HelloSC'. */
	timerService->setTimer(this, 4, (static_cast<sc::time> (200)), true);
	enseq_main_region_default();
	enseq_timer_sc_default();
	enseq_ui_sc_default();
	isExecuting = false;
}

void HelloSC::exit() {
	/* Deactivates the state machine. */
	if (isExecuting)
	{ 
		return;
	} 
	isExecuting = true;
	/* Default exit sequence for statechart HelloSC */
	exseq_main_region();
	stateConfVector[0] = HelloSC::State::NO_STATE;
	stateConfVectorPosition = 0;
	exseq_timer_sc();
	stateConfVector[1] = HelloSC::State::NO_STATE;
	stateConfVectorPosition = 1;
	exseq_ui_sc();
	stateConfVector[2] = HelloSC::State::NO_STATE;
	stateConfVectorPosition = 2;
	/* Exit action for state 'HelloSC'. */
	timerService->unsetTimer(this, 4);
	isExecuting = false;
}



