FROM registry.fedoraproject.org/fedora-toolbox:41

ARG NAME=emb22109-toolbox
ARG VERSION=41
LABEL com.github.containers.toolbox="true" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox(1) command" \
      summary="Image for creating Fedora Toolbx containers"

RUN dnf --assumeyes upgrade

COPY extra-packages /
RUN dnf --assumeyes install $(<extra-packages)
RUN rm /extra-packages

RUN dnf clean all

RUN sed -i -e 's/ ALL$/ NOPASSWD:ALL/' /etc/sudoers

RUN ln -s /run/host/var/data/aluno /data
RUN ln -s /run/host/var/data/aluno/emb22109 /emb22109
COPY ./rootfs_update.sh /usr/local/bin/
#RUN chmod a+x /usr/local/bin/rootfs_update.sh
