FROM registry.fedoraproject.org/fedora-toolbox:41

ARG NAME=dev-toolbox
ARG VERSION=41
LABEL com.github.containers.toolbox="true" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox(1) command" \
      summary="Image for creating Fedora Toolbx containers"

RUN dnf --assumeyes upgrade

COPY extra-packages /
RUN dnf --assumeyes install $(<extra-packages)
RUN rm /extra-packages

RUN wget https://update.code.visualstudio.com/latest/linux-rpm-x64/stable -O /code-latest-x64.rpm
RUN dnf --assumeyes install /code-latest-x64.rpm
RUN rm /code-latest-x64.rpm
RUN mkdir /usr/share/code/data
RUN chmod 777 /usr/share/code/data

RUN dnf clean all

RUN sed -i -e 's/ ALL$/ NOPASSWD:ALL/' /etc/sudoers

RUN ln -s /run/host/var/data/aluno /data
RUN ln -s /run/host/var/data/aluno/emb22109 /emb22109
RUN ln -s /run/host/var/data/aluno/prg22107 /prg22107
RUN ln -s /run/host/var/data/aluno/prg203405 /prg203405

RUN mkdir /install
COPY ./code-templates.tgz /install/
COPY ./setup_extensions.sh /usr/local/bin/

COPY ./rootfs_update.sh /usr/local/bin/
#RUN chmod a+x /usr/local/bin/rootfs_update.sh
